services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # .rar uzantısı kaldırıldı
    container_name: disk-storage-container
    ports:
      - "5000:5000"
    volumes:
      - ~/Downloads/DiskStorage:/shared_storage:rw  # kur.sh ile uyumlu
      - ./:/app
    environment:
      - FLASK_DEBUG=0  # Production için 0 yapıldı
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python main.py server  # Açık komut